### ISSUE TITLE
尝试跑了下前端的代码，发现是不全的，缺少相关的业务代码！

### ISSUE THREAD

**Issue by every-easy** [pastrale/course-scheduling-system-front#1]
![企业微信截图_16623474092098](https://user-images.githubusercontent.com/2618819/188353431-b827ce50-1bbd-4ae6-b07e-4a1218e9f6d8.png)

**Comment by sylviax26** [comment]
抱歉，router没有清理干净。

/view/raw/* 实质并没有用到

**Comment by sylviax26** [comment]
fixed in 7f4b95ec44fcc7f48c88ff008deed4e7686b1cc4

重新拉取最新代码即可
